.pragma library
// Pure controllers. No compositor, session transport, filesystem, or timers here.
var MAX_FRAMES=120, MAX_AGE_MS=30*60*1000, MAX_BYTES=512*1024, MIN_INTERVAL_MS=2000;
function finite(v,f){var n=Number(v);return isFinite(n)?n:f}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function camera(value){value=value||{};return {x:clamp(finite(value.x,0),-1000000,1000000),y:clamp(finite(value.y,0),-1000000,1000000),zoom:clamp(finite(value.zoom,1),.08,6),yaw:((finite(value.yaw,45)%360)+360)%360,tilt:clamp(finite(value.tilt,35.26438968),20,75)}}
function name(value){return String(value||'').replace(/[\u0000-\u001f\u007f]/g,'').replace(/\s+/g,' ').trim().slice(0,40)}
function target(value){var n=Number(value);return isFinite(n)&&Math.floor(n)===n&&n>0&&n<=100000?n:null}
function viewpoints(value){var seen={},out=[];((value&&value.viewpoints)||[]).slice(0,12).forEach(function(v){var n=name(v.name),k=n.toLowerCase();if(!n||seen[k])return;seen[k]=true;out.push({name:n,camera:camera(v.camera),targetDistrict:target(v.targetDistrict),savedAt:Math.max(0,finite(v.savedAt,0))})});return out}
function tourIds(districts){var seen={},out=[];(districts||[]).forEach(function(d){var id=target(d.id);if(id!==null&&!seen[id]){seen[id]=true;out.push(id)}});return out}
function nextTour(ids,index,districts){var present=tourIds(districts),i=index+1;while(i<ids.length&&present.indexOf(ids[i])<0)i++;return i<ids.length?{index:i,id:ids[i]}:null}
function opaque(value){return typeof value==='string'&&/^[A-Za-z0-9._:-]{1,128}$/.test(value)?value:''}
function agentKey(record){return String(record.provider||'Unknown')+':'+String(record.id||'')}
function publicClass(value){return typeof value==='string'&&/^[A-Za-z0-9._-]{1,80}$/.test(value)?value:'Unknown'}
function sourceLabel(value){return typeof value==='string'&&/^[A-Za-z0-9 ._:-]{1,80}$/.test(value)?value:'adapter'}
function agentStatus(value){var v=typeof value==='string'?{type:value}:value||{},type=typeof v.type==='string'&&/^[A-Za-z0-9_-]{1,40}$/.test(v.type)?v.type:'unknown';return {type:type,activeFlags:(Array.isArray(v.activeFlags)?v.activeFlags:[]).filter(function(f){return ['waitingOnApproval','waitingOnUserInput'].indexOf(f)>=0}).slice(0,2)}}
function statusText(value){var s=agentStatus(value);return s.type+s.activeFlags.map(function(f){return f==='waitingOnApproval'?' / approval pending':' / input pending'}).join('')}
function positive(v,max){var n=Number(v);return isFinite(n)&&Math.floor(n)===n&&n>=0&&n<=max?n:0}
function group(v){return ['development','entertainment','communication','research','system','mixed'].indexOf(v)>=0?v:'mixed'}
function tint(v){return typeof v==='string'&&/^#[0-9a-fA-F]{6}$/.test(v)?v:'#9e9e9e'}
function metadata(snapshot,agents){snapshot=snapshot||{};var districts=(snapshot.districts||[]).slice(0,512).map(function(d){return {id:positive(d.id,100000),monitor:positive(d.monitor,512),seed:positive(d.seed,4294967295),name:'District '+positive(d.id,100000),group:group(d.group),groupName:group(d.group),groupColor:tint(d.groupColor),count:0}}).filter(function(d){return d.id>0}),ids=districts.map(function(d){return d.id}),seen={};
 var windows=(snapshot.windows||[]).slice(0,512).map(function(w){return {address:opaque(w.address),workspace:positive(w.workspace,100000),monitor:positive(w.monitor,512),class:publicClass(w.class),app:publicClass(w.class),width:clamp(finite(w.width,0),0,20000),height:clamp(finite(w.height,0),0,20000),ownerCpu:{state:'unavailable',scope:'historical'},focused:false,urgent:false,floating:!!w.floating}}).filter(function(w){if(!w.address||seen[w.address]||ids.indexOf(w.workspace)<0)return false;seen[w.address]=true;return true}).sort(function(a,b){return a.address<b.address?-1:a.address>b.address?1:0});
 districts.forEach(function(d){d.count=windows.filter(function(w){return w.workspace===d.id}).length});districts.sort(function(a,b){return a.id-b.id});
 var agentSeen=Object.create(null),records=(agents||snapshot.agents||[]).slice(0,512).map(function(a){return {id:opaque(a.id||a.sessionId),parentId:opaque(a.parentId),familyId:opaque(a.familyId),isSubagent:a.isSubagent===true,isKimi3:a.isKimi3===true,workspace:positive(a.workspace,100000),status:agentStatus(a.status),source:sourceLabel(a.statusSource||a.source||a.provider||'adapter'),provider:publicClass(a.provider||'Unknown')}}).filter(function(a){var key=agentKey(a);if(!a.id||agentSeen[key])return false;agentSeen[key]=true;return true}).sort(function(a,b){var left=agentKey(a),right=agentKey(b);return left<right?-1:left>right?1:0});
 return {schema:1,boroughs:(snapshot.boroughs||[]).slice(0,512).map(function(b){return {id:positive(b.id,512),name:'Monitor '+positive(b.id,512)}}),districts:districts,windows:windows,agents:records,replay:true,telemetry:'historical-unavailable',truncated:(snapshot.windows||[]).length>512||(snapshot.districts||[]).length>512||(agents||snapshot.agents||[]).length>512};
}
function differences(previous,current,time){var events=[],old={},now={};function emit(kind,source,id,extra){if(events.length<1024)events.push(Object.assign({kind:kind,source:source,id:id,timestamp:time},extra||{}))}
 previous.windows.forEach(function(w){old[w.address]=w});current.windows.forEach(function(w){now[w.address]=w;if(!old[w.address])emit('window-observed','compositor',w.address,{workspace:w.workspace});else if(old[w.address].workspace!==w.workspace||old[w.address].monitor!==w.monitor)emit('window-membership-changed','compositor',w.address,{fromWorkspace:old[w.address].workspace,workspace:w.workspace,monitor:w.monitor})});previous.windows.forEach(function(w){if(!now[w.address])emit('window-no-longer-observed','compositor',w.address,{workspace:w.workspace})});
 var before=previous.districts.map(function(d){return d.id}),after=current.districts.map(function(d){return d.id});after.forEach(function(id){if(before.indexOf(id)<0)emit('district-observed','compositor',String(id))});before.forEach(function(id){if(after.indexOf(id)<0)emit('district-no-longer-observed','compositor',String(id))});
 old=Object.create(null);now=Object.create(null);previous.agents.forEach(function(a){old[agentKey(a)]=a});current.agents.forEach(function(a){var key=agentKey(a);now[key]=a;if(!old[key])emit('agent-observed',a.source,key,{sessionId:a.id,provider:a.provider,status:a.status});else if(JSON.stringify(old[key].status)!==JSON.stringify(a.status))emit('agent-status-reported',a.source,key,{sessionId:a.id,provider:a.provider,previous:old[key].status,status:a.status})});previous.agents.forEach(function(a){var key=agentKey(a);if(!now[key])emit('agent-no-longer-observed',a.source,key,{sessionId:a.id,provider:a.provider})});return events;
}
function createHistory(){return {frames:[],bytes:0,lastSample:0,baseline:null,paused:false,startedAt:0,dropped:0}}
function prune(history,now){while(history.frames.length&&(history.frames.length>MAX_FRAMES||now-history.frames[0].timestamp>MAX_AGE_MS||history.bytes>MAX_BYTES)){history.bytes-=history.frames[0].bytes;history.frames.shift();history.dropped++}return history}
function pause(history){history.baseline=null;history.paused=true;return history}
function observe(history,snapshot,agents,time){time=Math.max(history.lastSample,finite(time,Date.now()));prune(history,time);if(history.baseline&&time-history.lastSample<MIN_INTERVAL_MS)return false;var value=metadata(snapshot,agents),fingerprint=JSON.stringify(value);if(history.baseline&&fingerprint===history.baseline.fingerprint)return false;
 var hadBaseline=!!history.baseline,events=hadBaseline?differences(history.baseline.snapshot,value,time):[],boundary=hadBaseline?'':history.startedAt?'tracking-resumed':'tracking-started';history.lastSample=time;history.baseline={snapshot:value,fingerprint:fingerprint};if(!history.startedAt)history.startedAt=time;history.paused=false;var frame={timestamp:time,snapshot:value,events:events,boundary:events.length?'':boundary};frame.bytes=JSON.stringify(frame).length*2;
 if(frame.bytes>MAX_BYTES){history.dropped++;return false}history.frames.push(frame);history.bytes+=frame.bytes;prune(history,time);return true;
}
function frameAt(history,index){return history.frames[clamp(Math.floor(finite(index,0)),0,Math.max(0,history.frames.length-1))]||null}
