const fs=require('fs'),vm=require('vm'),assert=require('assert');
const context={};vm.createContext(context);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../CityV2.js'),'utf8').replace('.pragma library',''),context);
const c=context;
assert.equal(c.lampBrightness({state:'sampling',level:1}),.12);
assert.equal(c.lampBrightness({state:'unavailable',level:1}),.12);
assert.equal(c.lampBrightness({state:'measured',level:0}),.18);
assert.equal(c.lampBrightness({state:'measured',level:10}),.8);
assert(c.lampBrightness({state:'measured',level:.7})>c.lampBrightness({state:'measured',level:.2}));
const fixture={boroughs:[{id:0,name:'Display'}],districts:[{id:1,seed:1,monitor:0,count:1}],windows:[{address:'0x1',workspace:1,monitor:0,app:'Code',class:'Code',width:900,height:600,pid:42,ownerCpu:{state:'measured',percent:0,level:0}}]};
const scene=c.layout(fixture);c.transition({buildings:[]},scene,false,0);
const geometry=JSON.stringify([scene.bounds,scene.districts,scene.buildings.map(b=>[b.x,b.y,b.height,b.size,b.startX,b.startY,b.targetX,b.targetY])]);
const strokes=[];const ctx=new Proxy({stroke(){strokes.push(this.strokeStyle)}},{get(o,k){return k in o?o[k]:()=>{}}});
const palette={accent:'#ffffff',ink:'#eeeeee',neons:['#ffffff'],left:'#222222',right:'#111111',roof:'#333333',roofActive:'#555555'};
c.building(ctx,scene.buildings[0],palette,'',0,1,'');const dim=strokes.filter(s=>s.startsWith('rgba(255,220,168,'));strokes.length=0;
c.updateActivity(scene,[{address:'0x1',pid:42,ownerCpu:{state:'measured',percent:100,level:1}}]);
c.building(ctx,scene.buildings[0],palette,'',100,1,'');const bright=strokes.filter(s=>s.startsWith('rgba(255,220,168,'));
assert.equal(dim.length,bright.length);assert(dim.length>5);
dim.forEach((s,i)=>assert(parseFloat(s.split(',')[3])<parseFloat(bright[i].split(',')[3])));
assert.equal(JSON.stringify([scene.bounds,scene.districts,scene.buildings.map(b=>[b.x,b.y,b.height,b.size,b.startX,b.startY,b.targetX,b.targetY])]),geometry);
console.log('PASS bounded warm CPU lamp rendering; unavailable/sampling states; metric updates preserve geometry.');
