const fs=require('fs'),vm=require('vm'),assert=require('assert');const c={};vm.createContext(c);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../AgentCityV2.js'),'utf8').replace('.pragma library',''),c);
const s={districts:[{id:1,x:0,y:0}],buildings:[],roads:[],groups:[]};const agents=[{id:'parent-123',provider:'codex',status:{type:'idle'}},{id:'child-456',provider:'codex',parentId:'parent-123',status:{type:'active'}},{id:'unknown-789',provider:'claude',parentId:'missing'},{id:'cycle-a',provider:'codex',parentId:'cycle-b'},{id:'cycle-b',provider:'codex',parentId:'cycle-a'}];
const d=c.decorate(s,agents);assert.equal(s.districts.length,1);assert.equal(s.buildings.length,0);assert.equal(d.buildings.length,5);const p=d.buildings.find(b=>b.sessionId==='parent-123'),child=d.buildings.find(b=>b.sessionId==='child-456');assert(p&&child);assert.equal(p.workspace,child.workspace);assert(child.height<p.height);assert(d.roads.some(r=>r.parentKey===p.key&&r.childKey===child.key));assert(!d.roads.some(r=>r.childKey.includes('unknown')));assert(d.districts.slice(1).every(x=>x.kind==='agentFamily'&&x.virtualWorkspace&&x.id<0));assert(d.buildings.every(x=>x.kind==='agent'&&x.address===null&&x.ownerCpu.state==='unavailable'));assert.equal(c.records(agents.concat(agents)).length,5);assert.deepEqual(JSON.parse(JSON.stringify(c.decorate(s,[]))),s);assert.equal(c.records(Array.from({length:200},(_,i)=>({id:'x'+i,provider:'codex'}))).length,128);console.log('PASS actual-session courts, explicit parent links, missing-parent/cycle handling, no OS addresses/CPU inference, immutable desktop and bounded records.');
function verifyGeometry(scene,records){
 const courts=scene.districts.filter(d=>d.kind==='agentFamily'),buildings=scene.buildings.filter(b=>b.kind==='agent'),group=scene.groups.find(g=>g.key==='agent-sessions');
 assert.equal(buildings.length,records.length);
 for(const court of courts){assert(court.width>=180&&court.height>=180);assert.equal(court.worldBounds.maxX-court.worldBounds.minX,court.width);assert.equal(court.worldBounds.maxY-court.worldBounds.minY,court.height);for(const b of buildings.filter(b=>b.workspace===court.id)){assert(b.x-b.size/2>=court.worldBounds.minX+63);assert(b.x+b.size/2<=court.worldBounds.maxX-63);assert(b.y-b.size/2>=court.worldBounds.minY+63);assert(b.y+b.size/2<=court.worldBounds.maxY-63);assert.equal(b.reportedRoot,!b.agent.parentId);assert.equal(b.height,b.reportedRoot?105:65)}}
 for(let i=0;i<buildings.length;i++)for(let j=i+1;j<buildings.length;j++){const a=buildings[i],b=buildings[j];assert(Math.abs(a.x-b.x)>=(a.size+b.size)/2+1||Math.abs(a.y-b.y)>=(a.size+b.size)/2+1,'overlapping agent footprints '+a.key+' '+b.key)}
 for(let i=0;i<courts.length;i++)for(let j=i+1;j<courts.length;j++){const a=courts[i].worldBounds,b=courts[j].worldBounds;assert(a.maxX+95<=b.minX||b.maxX+95<=a.minX||a.maxY+95<=b.minY||b.maxY+95<=a.minY,'overlapping family courts')}
 assert.equal(group.worldBounds.minX,Math.min(...courts.map(d=>d.worldBounds.minX)));assert.equal(group.worldBounds.minY,Math.min(...courts.map(d=>d.worldBounds.minY)));assert.equal(group.worldBounds.maxX,Math.max(...courts.map(d=>d.worldBounds.maxX)));assert.equal(group.worldBounds.maxY,Math.max(...courts.map(d=>d.worldBounds.maxY)));assert.equal(group.width,group.worldBounds.maxX-group.worldBounds.minX);assert.equal(group.height,group.worldBounds.maxY-group.worldBounds.minY);assert.equal(group.labelWorld.x,group.x);assert(group.labelWorld.y<group.worldBounds.minY);
 const lookup=new Map(buildings.map(b=>[b.key,b]));for(const road of scene.roads.filter(r=>r.kind==='agent-link')){const child=lookup.get(road.childKey),parent=lookup.get(road.parentKey);assert(child&&parent);assert.equal(child.agent.provider,parent.agent.provider);assert.equal(String(child.agent.parentId),String(parent.sessionId));assert.equal(child.workspace,parent.workspace);assert.equal(road.worldA.x,parent.x);assert.equal(road.worldB.y,child.y)}
 return {courts,buildings,group};
}
const wide=[{id:'head',provider:'codex'}];for(let i=0;i<127;i++)wide.push({id:'sibling-'+String(i).padStart(3,'0'),provider:'codex',parentId:'head'});let geometry=verifyGeometry(c.decorate(s,wide),wide);assert.equal(geometry.courts.length,1);assert(geometry.courts[0].width>300&&geometry.courts[0].height>300);assert.equal(geometry.buildings.filter(b=>b.reportedRoot).length,1);
const deep=[{id:'head',provider:'codex'}];for(let i=1;i<=8;i++)deep.push({id:'generation-'+i,provider:'codex',parentId:i===1?'head':'generation-'+(i-1)});for(let i=0;i<119;i++)deep.push({id:'wide-child-'+i,provider:'codex',parentId:'head'});geometry=verifyGeometry(c.decorate(s,deep),deep);assert.equal(Math.max(...geometry.buildings.map(b=>b.agentDepth)),8);const level1=geometry.buildings.filter(b=>b.agentDepth===1),level2=geometry.buildings.filter(b=>b.agentDepth===2);assert(Math.min(...level2.map(b=>b.y))>Math.max(...level1.map(b=>b.y))+30);
const independent=Array.from({length:128},(_,i)=>({id:'independent-'+String(i).padStart(3,'0'),provider:i%2?'claude':'codex'}));geometry=verifyGeometry(c.decorate(s,independent),independent);assert.equal(geometry.courts.length,128);assert(geometry.group.width/geometry.group.height<2&&geometry.group.height/geometry.group.width<2);
const mixed=[];for(let f=0;f<12;f++){mixed.push({id:'family-'+f,provider:'codex'});for(let i=0;i<f;i++)mixed.push({id:'family-'+f+'-child-'+i,provider:'codex',parentId:'family-'+f})}geometry=verifyGeometry(c.decorate(s,mixed),mixed);assert.equal(geometry.courts.length,12);assert(new Set(geometry.courts.map(d=>d.width)).size>1);
const longChain=Array.from({length:128},(_,i)=>({id:'chain-'+String(i).padStart(3,'0'),provider:'codex',parentId:i?'chain-'+String(i-1).padStart(3,'0'):undefined}));geometry=verifyGeometry(c.decorate(s,longChain),longChain);assert.equal(Math.max(...geometry.buildings.map(b=>b.agentDepth)),127);assert(geometry.buildings.some(b=>b.depthClamped));
const cycleRows=[{id:'cycle-a',provider:'codex',parentId:'cycle-b'},{id:'cycle-b',provider:'codex',parentId:'cycle-a'},{id:'cycle-child',provider:'codex',parentId:'cycle-a'},{id:'orphan',provider:'claude',parentId:'absent'}];geometry=verifyGeometry(c.decorate(s,cycleRows),cycleRows);assert.equal(geometry.courts.length,2);assert(geometry.buildings.every(b=>!b.reportedRoot&&b.height===65));assert.equal(geometry.buildings.find(b=>b.sessionId==='cycle-child').agentDepth,1);
const explicit=[{id:'parent',provider:'codex',familyId:'family-a'},{id:'child',provider:'codex',familyId:'family-b',parentId:'parent'},{id:'other',provider:'codex',familyId:'family-a'},{id:'other',provider:'claude',familyId:'family-a'}];geometry=verifyGeometry(c.decorate(s,explicit),explicit);assert.equal(geometry.courts.length,2);assert.equal(c.decorate(s,explicit).roads.length,1);assert(geometry.courts.every(d=>d.familyId==='family-a'&&['codex','claude'].includes(d.familyProvider)));assert(d.districts.slice(1).every(x=>x.familyId===null),'No invented family scope for records without family metadata');
const source=JSON.stringify({scene:s,records:deep});const deterministic=c.decorate(s,deep);assert.equal(JSON.stringify(c.decorate(s,deep.slice().reverse())),JSON.stringify(deterministic));assert.equal(JSON.stringify({scene:s,records:deep}),source);
const largeDesktop={districts:[{id:1,x:500,y:0,width:900,height:900}],buildings:[],roads:[],groups:[]};geometry=verifyGeometry(c.decorate(largeDesktop,deep),deep);assert(geometry.group.worldBounds.minX>=largeDesktop.districts[0].x+450+320);
console.log('PASS 128 sibling/independent/deep/heterogeneous families; exact platform/group bounds; cumulative hierarchy rows; cycle/missing/conflicting family metadata; no invented parent links; deterministic immutable layout.');
