"""Native integrated controls on synthetic data; no host actions or private captures."""
import json,subprocess,time
from fixtures import city_fixture
from native_session import NativeSession,ROOT,clean_log
agents=[{'id':'11111111-1111-4111-8111-111111111111','provider':'codex','label':'Codex fixture parent','familyId':'fixture-family','parentId':None,'status':{'type':'idle','activeFlags':[]},'statusSource':'Protocol fixture','availability':'live','observedAt':'2026-10-06T00:00:00Z','capabilities':{'canReadReply':False,'canSend':False,'canOpen':False}}, {'id':'22222222-2222-4222-8222-222222222222','provider':'codex','label':'Codex fixture child','familyId':'fixture-family','parentId':'11111111-1111-4111-8111-111111111111','status':{'type':'notLoaded','activeFlags':[]},'statusSource':'Protocol fixture','availability':'stored','observedAt':'2026-10-06T00:00:00Z','capabilities':{'canReadReply':False,'canSend':False,'canOpen':False}}]
qml='''import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Wayland
import QtTest
import "CityV2.js" as City
ShellRoot {
 QA_GUARD
 DistrictsV2{id:d;testMode:true;preferMaximized:false;settings:({motion:false,edgePan:false,storedAgents:true})}
 Timer{interval:200;running:true;onTriggered:{d.open();d.ingest(FIXTURE);d.acceptAgents(AGENTS);console.log("READY")}}
 TestCase{id:qa;parent:d.testBody;name:"Integrated";when:false
  function checkCompare(actual,expected,message){if(JSON.stringify(actual)!==JSON.stringify(expected)){console.log("COMPARE_FAIL "+message+" actual="+JSON.stringify(actual)+" expected="+JSON.stringify(expected));throw new Error("COMPARE_FAIL "+message)}}
  function checkVerify(condition,message){if(!condition){console.log("VERIFY_FAIL "+message);throw new Error("VERIFY_FAIL "+message)}}
  function press(item){mouseClick(item,item.width/2,item.height/2);wait(80)}
  function test_all(){
   wait(500);checkCompare(d.scene.buildings.filter(function(b){return b.kind==="agent"}).length,2);checkCompare(d.scene.roads.filter(function(r){return r.kind==="agent-link"}).length,1)
   var camera=d.yaw;mousePress(d.testMap,160,170,Qt.RightButton);mouseMove(d.testMap,470,110,120);mouseRelease(d.testMap,470,110,Qt.RightButton);checkVerify(Math.abs(d.yaw-camera)>50);checkVerify(d.tilt>35);checkCompare(d.orbitDragging,false)
   for(var angle=0;angle<360;angle+=45){d.yaw=angle;wait(100);var building=d.scene.buildings.find(function(b){return b.kind!=="agent"});var p=City.project(building.x,building.y,building.height/2,d.orbitCamera);var hit=City.hit(d.scene,p.x,p.y,d.zoom,d.orbitCamera);checkVerify(!!hit,"Surface picking at angle "+angle)}
   d.resetCamera();checkCompare(d.yaw,45);checkVerify(Math.abs(d.tilt-35.26438968)<.001)
   d.inspectBuilding("0xa");d.openResources();checkCompare(d.panel,"resources");checkVerify(d.resourcesTarget.kind!=="agent");d.panel=""
   d.openPanel("lens");var count=d.snapshot.windows.length;d.testLens.selected({kind:"app",value:"code",label:"Code"});checkVerify(d.snapshot.windows.length<count);checkVerify(d.liveSnapshot.windows.length===count);checkVerify(d.scene.buildings.every(function(b){return b.appClass.toLowerCase()==="code"}));d.focusLens=null;d.renderSnapshot(d.liveSnapshot,d.agentRecords)
   d.openNavigation("views");checkCompare(d.testNavigation.panelOpen,true);d.testNavigation.close()
   d.testNavigation.startTour();checkCompare(d.testNavigation.touring,true);d.zoomAt(1.1,300,200);checkCompare(d.testNavigation.touring,false)
   d.testNavigation.startTour();d.testNavigation.stopTour("Fixture stop");checkCompare(d.testNavigation.touring,false)
   var nav=d.testNavigation;nav.clearHistory();var baseTime=Date.now();nav.observe(d.liveSnapshot,d.agentRecords,baseTime);var next=JSON.parse(JSON.stringify(d.liveSnapshot));next.windows.push({address:"0xfee",workspace:1,class:"org.fixture",app:"Fixture",monitor:0,height:300,width:400});nav.observe(next,d.agentRecords,baseTime+3000);checkVerify(nav.frameCount===2);nav.seek(0);checkCompare(d.replaying,true);var historicalCount=d.snapshot.windows.length;next.windows[0].ownerCpu={state:"measured",percent:99};d.liveSnapshot=next;d.testStoredAgents.clicked();checkCompare(d.snapshot.windows.length,historicalCount,"Stored view toggle keeps historical membership");checkVerify(d.snapshot.windows.every(function(w){return w.ownerCpu.state==="unavailable"}),"History never shows current CPU");d.testLens.selected({kind:"app",value:"code",label:"Code"});checkVerify(d.snapshot.windows.length<historicalCount);d.testLens.cleared();checkCompare(d.snapshot.windows.length,historicalCount,"Clearing historic lens restores raw frame");checkVerify(d.snapshot.windows.every(function(w){return w.address!=="0xfee"}),"No later live window leaks into history");d.selected="0xa";d.selectedDistrict=1;d.beginMove();checkCompare(d.moveDraft,null);var runs=d.testAction.running;d.navigate();checkCompare(d.testAction.running,runs);d.previewOrganization();checkVerify(d.panel!=="organize");nav.returnLive();checkCompare(d.replaying,false);checkCompare(d.selected,"");checkCompare(d.agentTarget,null)
   d.openAgent(d.agentRecords[1]);checkCompare(d.panel,"agents");checkVerify(d.testAgent.testSend.enabled===false);d.panel=""
   d.previewOrganization();checkCompare(d.panel,"organize");checkVerify(d.organizePlan.moves.length===0);d.panel=""
   var observed=Date.now(),quota={label:"Synthetic 5-hour window",state:"measured",freshness:"fresh",unit:"fraction",allowanceUsed:.7,allowanceRemaining:.3,source:"Controlled quota fixture",observedAt:observed,resetAt:observed+7200000,pace:{state:"behind",signedSeconds:-1800,source:"Controlled quota fixture",formula:"Verified fixed-window fixture",meaning:"pace-equivalent allowance credit",fixedWindow:true,windowStartAt:observed-10800000,recoveryAt:observed+1800000}};d.providerMetrics=[{provider:"codex",windows:[quota],ordinaryUsageAllowed:true}];
   for(var dim of [[912,512],[1093,614],[1600,1000]]){d.testViewport=Qt.size(dim[0],dim[1]);wait(100);d.showSettings=true;wait(50);checkVerify(d.testMotion.mapToItem(d.testBody,0,0).y+d.testMotion.height<d.testBody.height);d.showSettings=false;for(var panel of ["resources","lens","agents","providers"]){d.openPanel(panel);wait(80);if(panel==="providers"){checkVerify(d.testProviderPane.testHeadline.text.indexOf("behind")>=0,"Signed behind pace headline");checkVerify(d.testProviderPane.testWait.text.indexOf("if no additional usage")>=0,"Conditional wait assumption");checkVerify(d.testProviderPane.testRecovery.text.indexOf("UTC")>=0,"Actual local recovery timezone offset")}d.capture("OUT/"+panel+"-"+dim[0]+".png",1);wait(200);d.panel=""}d.openNavigation("tour");wait(80);d.capture("OUT/tour-"+dim[0]+".png",1);wait(200);d.testNavigation.close()}
   var same=d.agentRecords[1];d.openAgent(same);d.sessionDraft="Retained synthetic instruction";d.testAgent.draft=d.sessionDraft;d.testAgent.pendingMessageId="44444444-4444-4444-8444-444444444444";d.rememberAgentDraft();var pending=d.testAgent.pendingMessageId;d.acceptAgents(JSON.parse(JSON.stringify(d.agentRecords)));checkCompare(d.testAgent.pendingMessageId,pending,"Same-ID inventory refresh retains submission identity");d.panel="";d.openAgent(d.agentRecords[0]);d.openAgent(d.agentRecords[1]);checkCompare(d.testAgent.pendingMessageId,pending,"Selection round trip retains unchanged submission identity");checkCompare(d.sessionDraft,"Retained synthetic instruction");d.panel=""
   var targetA={key:"fixture-a",address:"0xa",ownerPid:42,app:"Fixture A"},targetB={key:"fixture-b",address:"0xb",ownerPid:43,app:"Fixture B"}
   d.openPanel("resources");d.resourcesTarget=targetA;d.resourcesContext={key:targetA.key,address:targetA.address,pid:targetA.ownerPid,generation:d.uiGeneration};d.resourcesResult=null
   d.testResourcesProcess.command=["python3","-c","import time,json;time.sleep(.15);print(json.dumps({'ok':True,'pid':42,'address':'0xa'}))"];d.testResourcesProcess.running=true;d.resourcesTarget=targetB;wait(300);checkCompare(d.resourcesResult,null,"Late owner A must not label owner B")
   d.resourcesContext={key:targetB.key,address:targetB.address,pid:targetB.ownerPid,generation:d.uiGeneration};d.testResourcesProcess.command=["python3","-c","import json;print(json.dumps({'ok':True,'pid':43,'address':'0xb'}))"];d.testResourcesProcess.running=true;wait(200);checkCompare(d.resourcesResult.address,"0xb","Exact context result accepted")
   d.panel="organize";d.organizeOperation="apply";d.organizeContext={generation:d.uiGeneration};d.organizeInput="{}";d.organizePlan={schema:1,planId:"fixture-partial",moves:[{},{}]};d.organizeReceipt=null
   d.testOrganizationProcess.command=["python3","-c","import json,sys;print(json.dumps({'ok':False,'schema':1,'planId':'fixture-partial','applied':1,'total':2,'stopped':True,'message':'Synthetic stale second fixture','items':[{'status':'applied'},{'status':'blocked'}]}));sys.exit(1)"];d.testOrganizationProcess.running=true;wait(250);checkCompare(d.organizeReceipt.applied,1,"Partial receipt retained despite code1");checkCompare(d.organizeReceipt.items[1].status,"blocked");d.panel=""
   d.openAgent(d.agentRecords[0]);checkCompare(d.sessionReply,null,"Opening details is metadata only");d.readAgent(d.agentRecords[0]);checkVerify(!d.testSessionsProcess.running,"No-capability direct read stays blocked")
   d.sessionOperation="reply";d.sessionContext={provider:d.agentTarget.provider,id:d.agentTarget.id,generation:d.uiGeneration,selectionGeneration:d.agentSelectionGeneration};d.sessionReply=null
   d.testSessionsProcess.command=["python3","-c","import time,json;time.sleep(.15);print(json.dumps({'ok':True,'text':'Synthetic late reply'}))"];d.testSessionsProcess.running=true;nav.seek(0);wait(300);checkCompare(d.sessionReply,null,"Late transcript rejected during history");checkCompare(d.agentTarget,null);nav.returnLive()
   d.openPanel("resources");d.resourcesTarget=targetB;d.resourcesContext={key:targetB.key,address:targetB.address,pid:targetB.ownerPid,generation:d.uiGeneration};d.resourcesResult=null
   d.testResourcesProcess.command=["python3","-c","import time,json;time.sleep(.15);print(json.dumps({'ok':True,'pid':43,'address':'0xb'}))"];d.testResourcesProcess.running=true;d.panel="";d.openPanel("resources");wait(300);checkCompare(d.resourcesResult,null,"Same-target close/reopen rejects old generation")
   d.panel="organize";d.organizeOperation="preview";d.organizeContext={generation:d.uiGeneration};d.organizeInput="{}";d.organizePlan=null
   d.testOrganizationProcess.command=["python3","-c","import time,json;time.sleep(.15);print(json.dumps({'ok':True,'plan':{'schema':1,'planId':'stale-preview'}}))"];d.testOrganizationProcess.running=true;d.panel="";d.panel="organize";wait(300);checkCompare(d.organizePlan,null,"Reopened organizer rejects old preview generation");d.panel=""
   var agentA=d.agentRecords[0],agentB=d.agentRecords[1];d.openAgent(agentA);d.testAgent.view="draft";d.sessionDraft="Original A";d.testAgent.draft=d.sessionDraft;wait(50);d.testAgent.testDraft.forceActiveFocus();d.testAgent.testDraft.text="Completed A";checkVerify(d.testAgent.editScheduled,"Draft edit queued before session switch");var bSaved=d.sessionDrafts[agentB.provider+":"+agentB.id];d.selectAgent(agentB);wait(50);checkCompare(d.sessionDrafts[agentA.provider+":"+agentA.id].draft,"Completed A","Root flush remembers last A edit before switch");checkCompare(d.sessionDraft,bSaved?bSaved.draft:"","A deferred edit never mutates B draft");d.selectAgent(null);d.panel=""
   var savedStates=d.sessionDrafts,states={};for(var i=0;i<16;i++)states["codex:pending-"+i]={draft:"Retained draft "+i,messageId:"retained-"+i,touched:i};d.selectAgent(null);d.sessionDrafts=states;d.openAgent({provider:"codex",id:"new-session",label:"Capacity fixture",capabilities:{canSend:true}});d.sessionDraft="New unsent draft";d.testAgent.draft=d.sessionDraft;wait(40);checkCompare(d.retainedSubmissions,16);checkVerify(!d.testAgent.testSend.enabled);checkCompare(d.testAgent.reviewDraft(),false);checkCompare(d.testAgent.newId(),"","Direct mint also fails closed at capacity");checkCompare(d.testAgent.pendingMessageId,"");d.selectAgent({provider:"codex",id:"pending-0",capabilities:{canSend:true}});wait(20);checkCompare(d.testAgent.pendingMessageId,"retained-0");checkVerify(d.testAgent.reviewDraft(),"Existing pending identity remains reviewable");d.sendAgent(d.agentTarget,"Altered retained payload","retained-0");checkVerify(d.sessionMessage.indexOf("identity does not match")>=0,"Central guard rejects a different payload for retained ID");d.testAgent.confirming=false;d.testAgent.replacePage("Edited retained draft");wait(40);checkCompare(d.retainedSubmissions,15);d.selectAgent(null);d.sessionDrafts=savedStates;d.panel=""
   var originalRecords=d.agentRecords;var gid="77777777-7777-4777-8777-777777777777",cid="88888888-8888-4888-8888-888888888888",piid="99999999-9999-4999-8999-999999999999";
   var grok={provider:"grok",id:gid,label:"Grok stored fixture",availability:"stored",status:{type:"unknown"},capabilities:{canReadReply:true,canSend:false}},claude={provider:"claude",id:gid+":a123",label:"Claude subagent fixture",familyId:gid,isSubagent:true,availability:"stored",status:{type:"unknown"},capabilities:{canReadReply:true,canSend:false}},kimi={provider:"pi",id:piid,label:"Kimi3 via Pi fixture",isKimi3:true,availability:"stored",status:{type:"unknown"},capabilities:{canReadReply:true,canSend:false}};
   d.acceptAgents([grok,claude,kimi]);d.selectAgent(null);press(d.testDeskButton);checkCompare(d.panel,"agents","Global Agent Desk button opens the shared pane");checkCompare(d.testAgent.selectorAgents.length,3,"Desk includes passed stored sessions");checkCompare(d.sessionReply,null,"Desk opening never reads a chat");d.openAgent(claude);checkCompare(d.agentTarget.id,claude.id,"Building routes exact native child identity into same Desk");checkCompare(d.panel,"agents");
   d.sessionReplyIdentity=claude.provider+":"+claude.id;d.sessionReply={provider:claude.provider,id:claude.id,text:"Synthetic selected reply",history:[{role:"assistant",text:"Synthetic selected reply"}]};wait(30);checkCompare(d.testAgent.replyMessages.length,1);d.selectAgent(grok);wait(20);checkCompare(d.sessionReply,null,"Different provider selection clears root-held reply");checkCompare(d.sessionReplyIdentity,"");checkCompare(d.testAgent.replyMessages.length,0);
   d.sessionOperation="reply";d.sessionContext={provider:grok.provider,id:grok.id,generation:d.uiGeneration,selectionGeneration:d.agentSelectionGeneration};d.testSessionsProcess.command=["python3","-c","import json;print(json.dumps({'ok':True,'provider':'grok','id':'wrong-session','text':'Withheld fixture'}))"];d.testSessionsProcess.running=true;wait(220);checkCompare(d.sessionReply,null,"Mismatching provider result identity is rejected");checkVerify(d.sessionMessage.indexOf("different session identity")>=0);
   d.sessionContext={provider:grok.provider,id:grok.id,generation:d.uiGeneration,selectionGeneration:d.agentSelectionGeneration};d.testSessionsProcess.command=["python3","-c","import time,json;time.sleep(.2);print(json.dumps({'ok':True,'provider':'grok','id':'"+grok.id+"','text':'Old selection fixture'}))"];d.testSessionsProcess.running=true;var epoch=d.agentSelectionGeneration;d.selectAgent(claude);d.selectAgent(grok);checkVerify(d.agentSelectionGeneration>epoch,"Selection round trip advances epoch");wait(350);checkCompare(d.sessionReply,null,"A to B to A never admits old A reply");d.readAgent(claude);checkVerify(d.sessionMessage.indexOf("exact session again")>=0,"Unselected direct read blocked");
   d.panel="";var beforeFilterWindows=d.snapshot.windows.length;d.filterProvider("kimi");checkCompare(d.deskAgents.length,1);checkCompare(d.deskAgents[0].provider,"pi","Kimi filter retains actual transport identity");checkCompare(d.scene.buildings.filter(function(b){return b.kind==="agent"}).length,1);checkCompare(d.snapshot.windows.length,beforeFilterWindows,"Provider filter preserves actual desktop windows");press(d.testProvidersButton);checkCompare(d.panel,"providers","Provider legend global entry");d.filterProvider("kimi");checkCompare(d.providerFilter,"");checkCompare(d.deskAgents.length,3);d.panel="";d.acceptAgents(originalRecords);d.selectAgent(null);
   d.testViewport=Qt.size(1440,900);d.selected="";d.selectedDistrict=-1;d.resetCamera();wait(200);d.capture("OUT/city.png",1);wait(300)
   d.close();checkVerify(!d.opened);checkVerify(!nav.touring);checkVerify(!nav.playing);console.log("INTEGRATED_PASS")
  }
 }
 IpcHandler{target:"harness";function run():void{Qt.callLater(function(){try{qa.test_all()}catch(error){console.log("INTEGRATED_FAILURE "+error+" "+error.stack);Qt.quit()}})}function status():string{return d.status()}function quit():void{Qt.callLater(Qt.quit)}}
}'''.replace('FIXTURE',json.dumps(city_fixture())).replace('AGENTS',json.dumps(agents))
folder=ROOT/'verification/integrated';folder.mkdir(parents=True,exist_ok=True);qml=qml.replace('OUT',str(folder))
def active():return json.loads(subprocess.check_output(['hyprctl','activewindow','-j'],text=True)).get('address')
before=active()
with NativeSession('integrated',qml)as session:
 session.marker('READY');session.ipc('run');session.marker('INTEGRATED_PASS',50);state=session.status();session.quit();clean_log(session.log());assert active()==before,'Fixture changed actual focus'
 print('PASS synthetic integrated native controls: orbit/tilt/reset, agent parentage, resources, immutable focus scopes, tour takeover, replay/live action guards, compact panels; focus unchanged.')
 (ROOT/'verification/integrated.json').write_text(json.dumps({'fixtureOnly':True,'actualNativeQtControls':True,'focusUnchanged':True,'status':state,'capturesSynthetic':True},indent=2))
