const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
function moduleFile(name){const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'..',name),'utf8').replace('.pragma library',''),ctx);return ctx}
const lens=moduleFile('LensV2.js'),resource=moduleFile('ResourcesV2.js');
const snapshot={boroughs:[{id:0},{id:1}],districts:[{id:1,monitor:0,group:'development',count:2},{id:2,monitor:1,group:'system',count:1},{id:3,monitor:0,group:'development',count:0}],windows:[{address:'0x1',class:'Code',workspace:1},{address:'0x2',class:'kitty',workspace:1},{address:'0x3',class:'kitty',workspace:2}],agents:[{provider:'codex',id:'a',familyId:'a'},{provider:'codex',id:'b',familyId:'a'},{provider:'codex',id:'c',familyId:'c'}]};
const before=JSON.stringify(snapshot);
assert.equal(lens.apply(snapshot,null),snapshot);
assert.equal(lens.apply(snapshot,{kind:'app',value:'KITTY'}).windows.length,2);
assert.equal(lens.apply(snapshot,{kind:'app',value:'kitty'}).districts[0].count,1);
assert.equal(lens.apply(snapshot,{kind:'app',value:'Code'}).boroughs.length,1);
assert.equal(lens.apply(snapshot,{kind:'district',value:3}).districts.length,1);
assert.equal(lens.apply(snapshot,{kind:'district',value:3}).windows.length,0);
assert.equal(lens.apply(snapshot,{kind:'category',value:'development'}).districts.length,2);
assert.equal(lens.apply(snapshot,{kind:'category',value:'development'}).windows.length,2);
const family=lens.apply(snapshot,{kind:'family',value:'a'});
assert.equal(family.windows.length,0);assert.equal(family.agents.length,2);
assert.equal(lens.counts(snapshot,{kind:'family',value:'a'}).shownAgents,2);
assert.equal(lens.agentFamily({pid:42}),null);assert.equal(lens.matchesAgent(snapshot.agents[1],{kind:'family',value:'a'}),true);
assert.equal(lens.options(snapshot.agents[0],null).length,1);
assert.equal(lens.options(snapshot.windows[0],snapshot.districts[0]).length,3);
for(const invalid of [{kind:'pid',value:42},{kind:'app',value:42},{kind:'district',value:'1'},{kind:'district',value:1.5},{kind:'family',value:''},{kind:'app',value:'a'.repeat(257)}])assert.equal(lens.normalize(invalid),null);
assert.equal(JSON.stringify(snapshot),before);
const collision={windows:[{address:'0xa',workspace:1,class:'terminal',agent:{id:'same-id',provider:'codex',familyId:'shared'}},{address:'0xb',workspace:1,class:'terminal',agent:{id:'same-id',provider:'claude',familyId:'shared'}}],districts:[{id:1,monitor:0,count:2}],boroughs:[{id:0}],agents:[{id:'same-id',provider:'codex',familyId:'shared'},{id:'same-id',provider:'claude',familyId:'shared'}]};
const collisionBefore=JSON.stringify(collision);
const scoped={kind:'family',value:'shared',provider:'codex'};
assert.equal(lens.normalize(scoped).provider,'codex');
assert.equal(lens.matchesAgent(collision.agents[0],scoped),true);
assert.equal(lens.matchesAgent(collision.agents[1],scoped),false);
assert.equal(lens.matches(collision.windows[0],scoped,{}),true);
assert.equal(lens.matches(collision.windows[1],scoped,{}),false);
assert.equal(lens.apply(collision,scoped).windows.length,1);
assert.equal(lens.apply(collision,scoped).agents.length,1);
assert.equal(lens.apply(collision,scoped).agents[0].provider,'codex');
assert.equal(lens.apply(collision,{kind:'family',value:'shared'}).agents.length,2);
assert.equal(lens.apply(collision,{kind:'family',value:'shared'}).windows.length,2);
assert.equal(JSON.stringify(collision),collisionBefore);
const node={kind:'agent',appClass:'codex',workspace:-1,agent:{id:'same-id',provider:'codex',familyId:'shared'}};
const court={id:-1,group:'development',virtualWorkspace:true,familyId:'shared',familyProvider:'codex'};
const virtualBefore=JSON.stringify([node,court]);
for(const choices of [lens.options(node,court),lens.options(node,null),lens.options(null,court)]){assert.equal(choices.length,1);assert.equal(choices[0].kind,'family');assert.equal(choices[0].value,'shared');assert.equal(choices[0].provider,'codex')}
assert.equal(lens.options({kind:'agent',appClass:'codex'},null).length,0);
assert.equal(lens.options(null,{id:-1,group:'development',virtualWorkspace:true}).length,0);
assert.equal(JSON.stringify([node,court]),virtualBefore);
for(const provider of [null,'',42,'x'.repeat(65)])assert.equal(lens.normalize({kind:'family',value:'shared',provider}),null);
assert.equal(resource.bytes(1048576),'1.0 MiB');assert.equal(resource.bytes(null),'Unavailable');
assert.equal(resource.workflow({status:{type:'running'},statusSource:'provider',observedAt:'2026-10-06T12:00:00Z',availability:'live'}).state,'running');
for(const fake of [{state:'busy',percent:50},{status:{type:'busy'},statusSource:'',observedAt:12,availability:'live'},{status:{type:'busy'},statusSource:'adapter',observedAt:12,availability:'unavailable'}])assert.equal(resource.workflow(fake),null);
const rows=resource.rows({ok:true,pid:42,startTime:100,observedAt:123000,residentBytes:null},null,{state:'measured',percent:125});
assert(rows.some(r=>r.value==='125.0% per core'));
assert(rows.some(r=>r.value.includes('No verified')||r.value.includes('no verified')));
assert(rows.filter(r=>r.label.startsWith('Resource scope')).map(r=>r.value).join('').includes('child processes excluded'));
const longRows=resource.paginateValues([{label:'Exact source',value:'source '.repeat(35)}]);
assert(longRows.every(r=>Array.from(r.value).length<=72));assert.equal(longRows.map(r=>r.value).join(''),'source '.repeat(35));
console.log('PASS pure immutable lens scopes, exact families, empty scopes, matching counts and resource/workflow separation.');
