const fs=require('fs'),vm=require('vm'),assert=require('assert');
function moduleAt(name){const c={};vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/../'+name,'utf8').replace(/^\.pragma library\s*/,''),c);return c}
const c=moduleAt('CityV2.js'),camera=moduleAt('CameraV2.js');
const yaws=[0,.001,1,44.999,45,89.999,90,90.001,135,179.999,180,225,269.999,270,270.001,315,359.999,360,-45,765];
for(const yaw of yaws)for(const tilt of [20,35.264389682754654,60,75]){
 const cam={yaw,tilt};
 for(const [x,y,z]of [[-500,200,0],[55,-70,28],[0,0,100],[930,700,-12]]){const p=c.project(x,y,z,cam),q=c.unproject(p.x,p.y,cam,z);assert(Math.abs(q.x-x)<1e-8&&Math.abs(q.y-y)<1e-8,'ground/height inverse yaw '+yaw)}
 const b={key:'one',x:0,y:0,size:32,height:80,growth:1},faces=c.buildingFaces(b,cam),o=c.orbit(cam);
 assert(faces.length>=2&&faces.length<=3);assert(faces.some(f=>f.name==='roof'));
 for(const f of faces){const dot=f.normal.x*o.s*o.ce+f.normal.y*o.c*o.ce+f.normal.z*o.se;assert(dot>0,'back face rendered');const mid=f.points.reduce((a,p)=>({x:a.x+p.x/f.points.length,y:a.y+p.y/f.points.length}),{x:0,y:0});assert(c.pointInPolygon(mid.x,mid.y,f.points));assert.equal(c.hit({groups:[],districts:[],buildings:[b]},mid.x,mid.y,1,cam).key,b.key)}
 const building={key:'a',x:0,y:0,size:60,height:170,growth:1},back={key:'b',x:-o.s*80,y:-o.c*80,size:40,height:100,growth:1};
 const all=[building,back].flatMap(b=>c.buildingFaces(b,cam).map(f=>({...f,key:b.key}))),ordered=c.orderSurfaces(all);
 for(let x=-60;x<=60;x+=5)for(let y=-180;y<=30;y+=5){const covering=ordered.filter(f=>c.pointInPolygon(x,y,f.points));if(!covering.length)continue;const nearest=covering.reduce((a,b)=>c.surfaceDepth(a.points,x,y)>c.surfaceDepth(b.points,x,y)?a:b);assert.equal(covering.at(-1).key,nearest.key,'painter disagrees with ray yaw '+yaw+' tilt '+tilt);assert.equal(c.hit({groups:[],districts:[],buildings:[building,back]},x,y,1,cam).key,nearest.key)}
}
const data={boroughs:[{id:0,name:'Display'}],districts:[{id:1,seed:1,monitor:0,count:1,group:'development',groupName:'Development',name:'Tools'}],windows:[{address:'0x1',workspace:1,class:'Code',app:'Code',height:700}]},scene=c.layout(data);
for(const yaw of yaws){const cam={yaw,tilt:20},bounds=c.bounds(scene,cam,.8);assert(Object.values(bounds).every(Number.isFinite));for(const b of scene.buildings)for(const p of c.face(b,cam))assert(p.x>=bounds.minX&&p.x<=bounds.maxX&&p.y>=bounds.minY&&p.y<=bounds.maxY);const g=scene.groups[0],p=c.groupLabel(scene,g,cam,.8);assert.equal(c.hit(scene,p.x,p.y-5,.8,cam).key,g.key);const d=scene.districts[0],dl=c.districtLabel(d,cam,.8),db=c.districtBounds(d,cam);assert(dl.y>db.maxY);assert(p.y<db.minY);}
const road={worldA:{x:10,y:20,z:0},worldB:{x:50,y:70,z:0},a:{x:999,y:999},b:{x:999,y:999}};assert.equal(c.roadPoints(road,{yaw:90,tilt:30}).a.x,c.project(10,20,0,{yaw:90,tilt:30}).x);
const base={x:3,y:5,zoom:1,yaw:350,tilt:30};assert.equal(camera.anchored(base,2,50,70,900,700).yaw,350);assert.equal(camera.orbit(base,-45,100).yaw,315);assert.equal(camera.orbit(base,720,-1).tilt,20);assert.equal(camera.reset(base).yaw,45);assert.equal(camera.reset(base).tilt,35.264389682754654);const to={...base,yaw:10,tilt:60},mid=camera.interpolate(base,to,.5);assert(mid.yaw>0&&mid.yaw<10,'yaw interpolates short path over zero');assert.equal(base.yaw,350);
// Drawing executes native canvas-compatible operations with finite coordinates, and text stays upright.
for(const yaw of yaws){const texts=[],operations=[],ctx={globalAlpha:1};for(const name of ['beginPath','moveTo','lineTo','closePath','fill','stroke','arc','ellipse','fillRect'])ctx[name]=(...args)=>{assert(args.filter(x=>typeof x==='number').every(Number.isFinite),name+' invalid coordinate');operations.push(name)};ctx.fillText=(text,x,y)=>{assert(Number.isFinite(x)&&Number.isFinite(y));texts.push(text)};const palette={accent:'#ffffff',ink:'#eeeeee',neons:['#ffffff','#000000'],left:'#222222',right:'#111111',roof:'#333333',roofActive:'#555555',ground:'#111111'};c.draw(ctx,scene,palette,'',1,0,false,1,null,'',{yaw,tilt:35});assert(operations.length>50);assert(texts.some(s=>s.includes('DEVELOPMENT')));assert.equal(ctx.globalAlpha,1)}
console.log('PASS: full360 projection/height inverse, four visible facade normals, exact surface-depth picking/painter order, cardinal edges, billboard bounds, world roads, instance-owned orbit/short-arc reset and native-compatible canvas draw.');
// A dense synthetic city includes taller far buildings and raised near platform sides.
for(const yaw of [0,.001,45,89.999,135,180,225,270,315])for(const tilt of [20,75]){
 const cam={yaw,tilt},buildings=Array.from({length:24},(_,i)=>({key:'dense'+i,x:(i%6)*42-120,y:Math.floor(i/6)*44-70,size:25,height:35+(i*19)%130,growth:1})),districts=[{id:1,x:0,y:0}],surfaces=buildings.flatMap(b=>c.buildingFaces(b,cam).map(f=>({...f,target:{type:'building',key:b.key}}))).concat(c.boxFaces(0,0,-12,120,120,12,cam).map(f=>({...f,target:{type:'district',key:1}}))),ordered=c.orderSurfaces(surfaces);
 for(let x=-170;x<170;x+=11)for(let y=-200;y<170;y+=13){const covering=ordered.filter(f=>c.pointInPolygon(x,y,f.points));if(!covering.length)continue;const nearest=covering.reduce((a,b)=>c.surfaceDepth(a.points,x,y)>c.surfaceDepth(b.points,x,y)+1e-6?a:b);assert.equal(covering.at(-1).target.key,nearest.target.key,'dense city depth order');assert.equal(c.hit({groups:[],districts,buildings},x,y,1,cam).key,nearest.target.key,'dense city picking')}
}
// Cached metric-only paints reuse ordering, while geometry/camera changes invalidate it.
function drawCount(scene,cam){let n=0;const ctx={};for(const k of ['beginPath','moveTo','lineTo','closePath','fill','stroke','arc','ellipse','fillRect','fillText'])ctx[k]=()=>n++;c.draw(ctx,scene,{accent:'#ffffff',ink:'#ffffff',neons:['#ffffff','#ffffff'],left:'#222222',right:'#111111',roof:'#333333',ground:'#222222'},'',1,0,false,1,null,'',cam);return n}
const full=drawCount(scene,{yaw:45,tilt:35}),order=scene._renderOrderCache.order;c.updateActivity(scene,[{address:'0x1',ownerCpu:{state:'measured',level:1}}]);drawCount(scene,{yaw:45,tilt:35});assert.strictEqual(scene._renderOrderCache.order,order);const light=drawCount(scene,{yaw:45,tilt:35,interactive:true});assert(light<full*.5,'interactive detail budget');assert.notStrictEqual(scene._renderOrderCache.order,order);
console.log('PASS: dense24-building/platform ray-depth parity at18 orientations; metric paint order cache; interactive real-geometry detail budget.');

const court={id:-1,x:1200,y:300,width:1200,height:600,kind:'agentFamily',seed:0,name:'Actual session family',group:'agent-sessions',groupName:'Agent Sessions',groupColor:'#ffffff'},courtScene={districts:[court],buildings:[],roads:[],boroughs:[],groups:[]};
for(const yaw of [0,45,90,135,180,225,270,315]){const cam={yaw,tilt:35},p=c.project(court.x+550,court.y+250,0,cam);assert.equal(c.hit(courtScene,p.x,p.y,1,cam).key,-1);const size=c.districtSize(court);assert.equal(size.halfWidth,600);assert.equal(size.halfDepth,300);const b=c.districtBounds(court,cam);assert(p.x>=b.minX&&p.x<=b.maxX&&p.y>=b.minY&&p.y<=b.maxY);assert(drawCount(courtScene,cam)>15)}
console.log('PASS: rectangular1200x600 actual-agent courts draw/pick/bounds across8 yawquadrants.');
